on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      id: build-image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:latest .

     # integrate trivy action to scan the docker image for vulnerabilities
    - name: Scan Docker image for vulnerabilities with Trivy
      uses: aquasecurity/trivy-action@v0.4.0
      with:
        image: ${{ secrets.ECR_REPOSITORY_URI }}:latest
        format: table
        severity: HIGH,CRITICAL
        exit-code: 1  # Fail the job if vulnerabilities are found

    - name: Tag Docker image
      run: |
        
        docker tag ${{ secrets.ECR_REPOSITORY_URI }}:latest ${{ secrets.ECR_REPOSITORY_URI }}:latest

    - name: Push Docker image to Amazon ECR
      run: |
        
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

