name: Python CI

on:
  push:
    branches:
      - main

concurrenry:
  grouo:production
  cancel-in-progress:true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - name: update my machine :
        run: sudo apt update

      - name: install nginx
        run: sudo apt install nginx 

      - name: start the nginx
        run: sudo systemctl start nginx

      
