name: Python CI

on:
  push:
    branches:
      - main
    

concurrency:
  grouo: prod
  cancel-in-progress: true

strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
     
      - name: install nginx
        run: sudo apt install nginx 

      - name: start the nginx
        run: sudo systemctl start nginx

      
